# Generated by Django 5.1 on 2025-04-23 11:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('age', models.IntegerField(default=0)),
                ('email', models.EmailField(max_length=254)),
                ('passport_number', models.CharField(max_length=9, unique=True)),
                ('date_of_birth', models.DateTimeField(default=datetime.datetime.now)),
                ('registrated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
