# Generated by Django 5.2 on 2025-04-23 11:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usermodel',
            options={'verbose_name': 'Foydalanuvchi', 'verbose_name_plural': 'Foydalanuvchilar'},
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='date_of_birth',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 23, 16, 49, 26, 129752)),
        ),
        migrations.AlterModelTable(
            name='usermodel',
            table='users',
        ),
    ]
