# Generated by Django 5.2 on 2025-04-25 11:41

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_usermodel_date_of_birth_coursemodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursemodel',
            name='students',
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='date_of_birth',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 25, 16, 41, 43, 459029)),
        ),
        migrations.CreateModel(
            name='CourseStudentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.coursemodel')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.usermodel')),
            ],
            options={
                'verbose_name': 'Kursga yozilgan ',
                'verbose_name_plural': 'Kursga Yozilganlar',
                'db_table': 'students_course',
            },
        ),
    ]
